services:
  whatsmyip:
    container_name: whatsmyip
    build:
      context: .
      args:
        IP2LOCATION_TOKEN: ${IP2LOCATION_TOKEN:-}
    image: code.paulg.it/paulgit/whatsmyip
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    restart: unless-stopped

